"""add rate

Revision ID: 1c900eae85b6
Revises: 181cce6cf248
Create Date: 2024-10-13 13:07:00.883111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c900eae85b6'
down_revision: Union[str, None] = '181cce6cf248'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('comments', sa.Column('average_rating', sa.Float(), nullable=True))
    op.drop_column('comments', 'modified')
    op.drop_column('comments', 'rate_count')
    op.drop_column('comments', 'rate_sum')
    op.drop_column('comments', 'rate')
    op.add_column('photos', sa.Column('average_rating', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'average_rating')
    op.add_column('comments', sa.Column('rate', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('comments', sa.Column('rate_sum', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('comments', sa.Column('rate_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('comments', sa.Column('modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('comments', 'average_rating')
    op.drop_column('comments', 'updated_at')
    # ### end Alembic commands ###
