"""add photo_id

Revision ID: 37747b16d397
Revises: 60bea5fac42f
Create Date: 2024-10-12 22:53:18.048382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37747b16d397'
down_revision: Union[str, None] = '60bea5fac42f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('public_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'public_id')
    # ### end Alembic commands ###
