"""Init-2

Revision ID: 60f90e07c7b2
Revises: 57fe92f5e06a
Create Date: 2024-10-05 13:17:03.308037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60f90e07c7b2'
down_revision: Union[str, None] = '57fe92f5e06a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('img_origin', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'images', ['img_origin'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'img_origin')
    # ### end Alembic commands ###
