"""add photo_ratings to user

Revision ID: a018142f4dcc
Revises: 61cac9ec11f8
Create Date: 2024-10-14 15:23:27.724583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a018142f4dcc'
down_revision: Union[str, None] = '61cac9ec11f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment_ratings')
    op.drop_index('ix_photo_links_id', table_name='photo_links')
    op.drop_table('photo_links')
    op.drop_column('comments', 'average_rating')
    op.add_column('photo_transformations', sa.Column('image_url', sa.String(), nullable=False))
    op.drop_column('photo_transformations', 'transformed_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo_transformations', sa.Column('transformed_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('photo_transformations', 'image_url')
    op.add_column('comments', sa.Column('average_rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.create_table('photo_links',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('original_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('transformed_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('qr_code_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='photo_links_pkey')
    )
    op.create_index('ix_photo_links_id', 'photo_links', ['id'], unique=False)
    op.create_table('comment_ratings',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], name='comment_ratings_comment_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='comment_ratings_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'comment_id', name='comment_ratings_pkey')
    )
    # ### end Alembic commands ###
