"""Опис змін

Revision ID: ade25286cdc0
Revises: b61c13621c2a
Create Date: 2024-10-12 12:47:47.467751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ade25286cdc0'
down_revision: Union[str, None] = 'b61c13621c2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_url', sa.String(), nullable=False),
    sa.Column('transformed_url', sa.String(), nullable=False),
    sa.Column('qr_code_url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photo_links_id'), 'photo_links', ['id'], unique=False)
    op.add_column('photos', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('photos', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'updated_at')
    op.drop_column('photos', 'created_at')
    op.drop_index(op.f('ix_photo_links_id'), table_name='photo_links')
    op.drop_table('photo_links')
    # ### end Alembic commands ###
