"""Add ban to User

Revision ID: e2a874ec1bbf
Revises: 22e0a92d7f8a
Create Date: 2024-10-08 20:09:36.986553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2a874ec1bbf'
down_revision: Union[str, None] = '22e0a92d7f8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('rate_sum', sa.Integer(), nullable=True))
    op.add_column('comments', sa.Column('rate_count', sa.Integer(), nullable=True))
    op.alter_column('comments', 'rate',
               existing_type=sa.INTEGER(),
               type_=sa.DECIMAL(),
               existing_nullable=True)
    op.add_column('users', sa.Column('banned', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('photo_count', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('comment_count', sa.Integer(), nullable=True))
    op.drop_column('users', 'rate')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('rate', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('users', 'comment_count')
    op.drop_column('users', 'photo_count')
    op.drop_column('users', 'banned')
    op.alter_column('comments', 'rate',
               existing_type=sa.DECIMAL(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('comments', 'rate_count')
    op.drop_column('comments', 'rate_sum')
    # ### end Alembic commands ###
